### ISSUE TITLE
Data flow doesn't show on bosh-lite

### ISSUE THREAD

**Issue by bodymindarts** [cloudfoundry-community/bolo-boshrelease#14]
Second row, left side.

<img width="1279" alt="screenshot 2016-06-27 11 29 43" src="https://cloud.githubusercontent.com/assets/8533296/16375198/89973d32-3c5a-11e6-858d-34196f71c8f6.png">

**Comment by jhunt** [comment]
I think data-flow is actually broken in general.  I've noticed similar issues on other IaaS deployments.

**Comment by jhunt** [comment]
Yeah, definitely broken.  PR forthcoming.

**Comment by jhunt** [comment]
or maybe not a PR, and just a commit / push to master.
