### ISSUE TITLE
Graphs with (.*-)?<ITEM>-.* are not showing up

### ISSUE THREAD

**Issue by bodymindarts** [cloudfoundry-community/bolo-boshrelease#16]
After deploying this to bosh-lite graps like [this one](https://github.com/cloudfoundry-community/bolo-boshrelease/blob/master/jobs/gnossis/templates/config/default_graphs.yml#L331) that contain `<ITEM>` in the name are not being displayed in the gnossis front end. Only graphs without `<ITEM>` are visible.

**Comment by jhunt** [comment]
What collectors are you running?

**Comment by bodymindarts** [comment]
Just default, so I guess that means only `linux`

**Comment by jhunt** [comment]
the specific graph you called out is a per-process CPU usage graph, which will only show up if you define per-process monitoring.  Are you seeing other <ITEM> graphs like [this one](https://github.com/cloudfoundry-community/bolo-boshrelease/blob/master/jobs/gnossis/templates/config/default_graphs.yml#L623)?
