### ISSUE TITLE
Turning on RRDCached fails

### ISSUE THREAD

**Issue by jhunt** [cloudfoundry-community/bolo-boshrelease#17]
Tried to create a new deployment of Bolo this morning, and set `cached: true` on the `rrd` and `gnossis` jobs, to no avail.  The graph images were corrupt, and the data wasn't being collected (although valid RRD files were being built).

I think this is a wiring problem with where the rrdcached socket file (UNIX domain socket) gets put, vs. where everything else is told to look for it.

Turning off caching `cached: false` "fixed" the problem, to the detriment of disk IO performance...

**Comment by geofffranks** [comment]
I think this was an issue with bolo-deployment templates for genesis. rrdcached appears to be working for me now that the job template was added. The corrupt images were fixed in gnossis v0.6.
